# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20)),
                ('moviesign', models.CharField(max_length=20)),
                ('movieii', models.CharField(max_length=20)),
            ],
        ),
    ]
