# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieii',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='moviesign',
            field=models.CharField(max_length=100),
        ),
    ]
