# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-26 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrr', '0002_auto_20190426_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieii',
        ),
    ]
